language: python
python:
    - "3.6"      # current default Python on Travis CI
    - "3.7"
    - "3.8"
jobs:
    allow_failures:
        - python: "3.8-dev"  # 3.8 development branch
        - python: "nightly"  # nightly build
# command to install dependencies
before_install:
    - python --version
    - pip install codecov
install:
    - pip install .
# command to run tests
script:
    - pytest
after_success:
    - codecov
